# A basic redirect rule
[[redirects]]
  from = "/post/dsm2-viz-tool/"
  to = "/post/deploy-shiny-electron/"
  
[[redirects]]
  from = "/post/shiny-scorekeeper-datatable-crud/"
  to = "/post/dt-datatable-crud/"
  
[[redirects]]
  from = "/post/generate-random-numbers-r-racket/"
  to = "/post/generating-random-numbers-r-racket/"